Fix markdown so that it has a complete quote style on the license
duolingo/rtl-viewpager pull request #6
Opened 2017-07-25 21:26 UTC by tasomaniac

2017-07-25 23:00 UTC, ataulm approved these changes

2017-07-26 07:16 UTC, DavidDTA requested changes

2017-07-26 07:16 UTC, DavidDTA commented on README.md
> +> A copy of the license is also available in the [license file](LICENSE).
This is not part of the quote.

2017-07-26 07:34 UTC, DavidDTA approved these changes

2017-07-26 07:34 UTC, merged

2017-07-26 07:34 UTC, tasomaniac commented on README.md
> +> A copy of the license is also available in the [license file](LICENSE).
Oh didn't realize that. Fixed it. Thank you for the awesome library